### PR TITLE
check_alignment: ensure that alignment is a positive integer

### LINKED ISSUE #140: Crash in cstub for check_alignment_bigstring
When you pass a `0` argument to `check_alignment` the process crashes due to a division-by-zero error in the c stub.

.mli:
```ocaml
val check_alignment : t -> int -> bool
(** [check_alignment cstr alignment] is [true] if the first byte stored
    within [cstr] is at a memory address where [address mod alignment = 0],
    [false] otherwise.
    Typical uses are to check a buffer is aligned to a page or disk sector
    boundary. *)
```

cstruct.ml:
```ocaml
external check_alignment_bigstring : buffer -> int -> int -> bool = "caml_check_alignment_bigstring"

let check_alignment t alignment = check_alignment_bigstring t.buffer t.off alignment
```

cstruct_stubs.c:
```c
CAMLprim value
caml_check_alignment_bigstring(value val_buf, value val_ofs, value val_alignment)
{
  uint64_t address = (uint64_t) (Caml_ba_data_val(val_buf) + Long_val(val_ofs));
  int alignment = Int_val(val_alignment);
  return Val_bool(address % alignment == 0);
}
```

When `val_alignment` is `0` this crashes the program.

### PR DESCRIPTION
**Pull request by avsm**
fixes #140

### CODE REVIEW

File: lib/cstruct.ml [hunk 1]
```diff
@@ -103,7 +103,10 @@ let check_bounds t len =
 
 external check_alignment_bigstring : buffer -> int -> int -> bool = "caml_check_alignment_bigstring"
 
-let check_alignment t alignment = check_alignment_bigstring t.buffer t.off alignment
+let check_alignment t alignment =
+  if alignment > 0 then
+    check_alignment_bigstring t.buffer t.off alignment
+  else raise (Invalid_argument "check_alignment must be positive integer")
```
Comment (rgrinberg) [inline lib/cstruct.ml]: no love for `invalid_arg`?

Comment (avsm) [inline lib/cstruct.ml]: fixed in 80428ed
